# Generated by Django 5.2.4 on 2025-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
