# Generated by Django 5.2.4 on 2025-08-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_businesssettings_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='plan_actual',
            field=models.CharField(default='basico', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='monthly_cost',
            field=models.DecimalField(decimal_places=2, default=299.00, max_digits=8),
        ),
    ]
