# Generated by Django 5.2.4 on 2025-08-09 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20250808_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_pos', models.BooleanField(default=True, verbose_name='Acceso al Punto de Venta')),
                ('can_access_inventory', models.BooleanField(default=True, verbose_name='Acceso al Inventario')),
                ('can_access_reports', models.BooleanField(default=False, verbose_name='Acceso a Reportes')),
                ('can_access_settings', models.BooleanField(default=False, verbose_name='Acceso a Configuración')),
                ('can_add_products', models.BooleanField(default=True, verbose_name='Agregar Productos')),
                ('can_edit_products', models.BooleanField(default=True, verbose_name='Editar Productos')),
                ('can_delete_products', models.BooleanField(default=False, verbose_name='Eliminar Productos')),
                ('can_adjust_stock', models.BooleanField(default=True, verbose_name='Ajustar Stock')),
                ('can_process_sales', models.BooleanField(default=True, verbose_name='Procesar Ventas')),
                ('can_apply_discounts', models.BooleanField(default=False, verbose_name='Aplicar Descuentos')),
                ('can_void_sales', models.BooleanField(default=False, verbose_name='Cancelar Ventas')),
                ('can_access_cash_register', models.BooleanField(default=True, verbose_name='Acceso a Caja')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Gestionar Usuarios')),
                ('can_view_financial_reports', models.BooleanField(default=False, verbose_name='Ver Reportes Financieros')),
                ('can_backup_data', models.BooleanField(default=False, verbose_name='Respaldar Datos')),
                ('max_sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto máximo de venta')),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% máximo de descuento')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=480, verbose_name='Timeout de sesión (minutos)')),
                ('require_pin_for_sensitive', models.BooleanField(default=False, verbose_name='Requiere PIN para operaciones sensibles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permisos de Usuario',
                'verbose_name_plural': 'Permisos de Usuarios',
                'unique_together': {('user', 'business')},
            },
        ),
    ]
