# Generated by Django 5.2.4 on 2025-12-06 18:38

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_felipa_superuser(apps, schema_editor):
    """Create felipa superuser for admin access"""
    User = apps.get_model('accounts', 'User')

    # Check if user already exists
    if not User.objects.filter(username='felipa').exists():
        User.objects.create(
            username='felipa',
            email='felipa@posmex.com',
            password=make_password('189.136'),
            is_staff=True,
            is_superuser=True,
            is_active=True,
            first_name='Felipa',
        )
        print('✓ Superusuario felipa creado exitosamente')
    else:
        # Update existing user to ensure correct permissions
        user = User.objects.get(username='felipa')
        user.password = make_password('189.136')
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save()
        print('✓ Superusuario felipa actualizado exitosamente')


def reverse_create_felipa(apps, schema_editor):
    """Remove felipa superuser"""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(username='felipa').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpermissions'),
    ]

    operations = [
        migrations.RunPython(create_felipa_superuser, reverse_create_felipa),
    ]
