# Generated by Django 5.2.4 on 2025-08-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_producto_categoria_producto_created_by_and_more'),
    ]

    operations = [
    ]
