# Generated by Django 5.2.4 on 2025-08-09 08:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpermissions'),
        ('pos', '0004_fix_categoria_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_tarjetas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('notas_apertura', models.TextField(blank=True, null=True)),
                ('notas_cierre', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='resumendiario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resumendiario',
            name='business',
        ),
        migrations.RemoveField(
            model_name='resumendiario',
            name='vendedor',
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['business', 'nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelOptions(
            name='ventadetalle',
            options={'ordering': ['venta', 'id'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Venta'},
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='pos_product_busines_3188f8_idx',
            old_name='pos_producto_bus_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='pos_product_busines_f44465_idx',
            old_name='pos_producto_bus_nombre_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='pos_product_busines_15fc20_idx',
            old_name='pos_producto_bus_activo_idx',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='cantidad_vendida',
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='codigo_producto',
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='total',
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('devuelta', 'Devuelta')], default='completada', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(default='VENTA-DEFAULT', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('credito', 'Crédito'), ('mixto', 'Mixto')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='pos.sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='ticket_impreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='descuento_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='pos.producto'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.venta'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['business', 'fecha_creacion'], name='pos_venta_busines_482838_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['business', 'estado'], name='pos_venta_busines_5f9128_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sucursal', 'fecha_creacion'], name='pos_venta_sucursa_10d53b_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario', 'fecha_creacion'], name='pos_venta_usuario_856ac4_idx'),
        ),
        migrations.AddField(
            model_name='caja',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='pos.sucursal'),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuario_apertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuario_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='accounts.business'),
        ),
        migrations.DeleteModel(
            name='ResumenDiario',
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['business', 'fecha_apertura'], name='pos_caja_busines_88a6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['sucursal', 'estado'], name='pos_caja_sucursa_6f2403_idx'),
        ),
    ]
