# Generated by Django 5.2.4 on 2025-11-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_subscription_models'),
        ('pos', '0006_movimientostock'),
    ]

    operations = [
    ]
