# Generated by Django 5.2.4 on 2025-11-21 23:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpermissions'),
        ('pos', '0007_merge_0002_subscription_models_0006_movimientostock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto del gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('gasto_operativo', 'Gasto Operativo'), ('retiro', 'Retiro'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto de Caja',
                'verbose_name_plural': 'Gastos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('status', models.CharField(choices=[('nuevo', '🆕 Nuevo Lead'), ('mensaje_enviado', '📱 Mensaje Enviado'), ('contactado', '💬 Contactado'), ('pago_pendiente', '⏳ Pago Pendiente'), ('pago_completado', '💰 Pago Completado'), ('link_enviado', '🔗 Link Enviado'), ('registro_completo', '✅ Registro Completo'), ('activo', '🚀 Usuario Activo'), ('vencido', '⚠️ Suscripción Vencida'), ('cancelado', '❌ Cancelado')], default='nuevo', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('mensaje_enviado_at', models.DateTimeField(blank=True, null=True, verbose_name='Mensaje enviado')),
                ('contactado_at', models.DateTimeField(blank=True, null=True, verbose_name='Contactado')),
                ('pago_pendiente_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago pendiente desde')),
                ('pago_completado_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago completado')),
                ('link_enviado_at', models.DateTimeField(blank=True, null=True, verbose_name='Link enviado')),
                ('registro_completo_at', models.DateTimeField(blank=True, null=True, verbose_name='Registro completado')),
                ('registration_token', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Token de registro')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token expira')),
                ('token_used', models.BooleanField(default=False, verbose_name='Token usado')),
                ('token_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Token usado en')),
                ('notes', models.TextField(blank=True, verbose_name='Notas administrativas')),
                ('source', models.CharField(default='formulario_web', max_length=50, verbose_name='Origen')),
            ],
            options={
                'verbose_name': 'Registro de Usuario',
                'verbose_name_plural': 'Gestión de Usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='movimientostock',
            new_name='pos_movimie_busines_140103_idx',
            old_name='pos_movimie_busines_a60e48_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientostock',
            new_name='pos_movimie_product_20a5ee_idx',
            old_name='pos_movimie_product_b3e965_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientostock',
            new_name='pos_movimie_busines_80e923_idx',
            old_name='pos_movimie_busines_ecc53e_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientostock',
            new_name='pos_movimie_venta_i_009656_idx',
            old_name='pos_movimie_venta_i_5f6c6f_idx',
        ),
        migrations.AddField(
            model_name='caja',
            name='efectivo_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='hora_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='monto_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='gastocaja',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_caja', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='gastocaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.business', verbose_name='Negocio'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='pos_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario POS'),
        ),
        migrations.AddField(
            model_name='userregistrationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userregistrationlog',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pos.userregistration'),
        ),
        migrations.AddIndex(
            model_name='gastocaja',
            index=models.Index(fields=['business', 'fecha'], name='pos_gastoca_busines_a75019_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocaja',
            index=models.Index(fields=['business', 'tipo'], name='pos_gastoca_busines_d84255_idx'),
        ),
    ]
