# Generated by Django 5.2.4 on 2025-11-22 18:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpermissions'),
        ('pos', '0008_user_management_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto del gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('gasto_operativo', 'Gasto Operativo'), ('retiro', 'Retiro'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto de Caja',
                'verbose_name_plural': 'Gastos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RenameIndex(
            model_name='movimientostock',
            new_name='pos_movimie_busines_140103_idx',
            old_name='pos_movimie_busines_a60e48_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientostock',
            new_name='pos_movimie_product_20a5ee_idx',
            old_name='pos_movimie_product_b3e965_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientostock',
            new_name='pos_movimie_busines_80e923_idx',
            old_name='pos_movimie_busines_ecc53e_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientostock',
            new_name='pos_movimie_venta_i_009656_idx',
            old_name='pos_movimie_venta_i_5f6c6f_idx',
        ),
        migrations.AddField(
            model_name='caja',
            name='efectivo_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='hora_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='monto_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='gastocaja',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_caja', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='gastocaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gastocaja',
            index=models.Index(fields=['business', 'fecha'], name='pos_gastoca_busines_a75019_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocaja',
            index=models.Index(fields=['business', 'tipo'], name='pos_gastoca_busines_d84255_idx'),
        ),
    ]
