# Generated by Django 5.2.4 on 2025-12-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_add_caja_missing_fields'),
    ]

    operations = [
        # Solo agregar campos nuevos a UserRegistration
        # Saltear creación de GastoCaja porque ya existe en producción
        migrations.AddField(
            model_name='userregistration',
            name='fecha_corte',
            field=models.DateField(
                blank=True,
                help_text='Fecha de vencimiento del contrato. Se calcula automáticamente como fecha_inicio + meses_contratados.',
                null=True,
                verbose_name='Fecha de corte'
            ),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='fecha_inicio_contrato',
            field=models.DateField(
                blank=True,
                help_text='Fecha de inicio del contrato. Se calcula automáticamente.',
                null=True,
                verbose_name='Fecha inicio de contrato'
            ),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='meses_contratados',
            field=models.IntegerField(
                blank=True,
                help_text='Cantidad de meses del contrato. Si está vacío, el usuario no tiene cobro.',
                null=True,
                verbose_name='Meses contratados'
            ),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='monto_pagado',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Monto total pagado por el cliente. Si está vacío, no hay cobro.',
                max_digits=10,
                null=True,
                verbose_name='Monto pagado'
            ),
        ),
    ]
