# Generated by Django 5.2.4 on 2025-12-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_merge_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock mínimo'),
        ),
    ]
