# Generated by Django 5.2.4 on 2026-02-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_change_stock_minimo_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='referencia_transferencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de transferencia'),
        ),
    ]
